publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.785]
    pos2: [0, 0]
    pos3: [-0.785, -0.785]
    pos4: [0, 0]

    joints:
     - ur_wrist_1_joint
     - ur_wrist_2_joint

    check_starting_point: false
    starting_point_limits:
      ur_wrist_1_joint: [-0.1,0.1]
      ur_wrist_2_joint: [-0.1,0.1]
